services:
  postgres:
    image: postgres:16-alpine
    container_name: natta-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: natta
      POSTGRES_USER: natta
      POSTGRES_PASSWORD: natta
    ports:
      - "5432:5432"
    volumes:
      - natta-postgres-data:/var/lib/postgresql/data

volumes:
  natta-postgres-data:
